// <auto-generated />
namespace CatStore.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class first_start : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_start));
        
        string IMigrationMetadata.Id
        {
            get { return "201802011811253_first_start"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
